version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ../data/prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ../data/grafana_data:/var/lib/grafana
      - ./grafana-config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana-config/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-config/dashboard-files:/var/lib/grafana/dashboard-files
    ports:
      - "3001:3001"
    command: ["--config", "/etc/grafana/grafana.ini"]
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../data/caddy_data:/data
volumes:
  prometheus_data:
  grafana_data:
  caddy_data: