version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ../data/jellyfin_data/config:/config
      - ../data/jellyfin_data/cache:/cache
      - type: bind
        source: ../media
        target: /media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.cesaratteh.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=Pdt/UTC
      - WEBUI_PORT=8095
      - TORRENTING_PORT=6881
    volumes:
      - ../data/qbittorrent_data/config:/config
      - ../media/downloads:/downloads
    ports:
      - 8095:8095
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ../data/prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ../data/grafana_data:/var/lib/grafana
      - ./grafana-config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana-config/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-config/dashboard-files:/var/lib/grafana/dashboard-files
    ports:
      - "3001:3001"
    command: ["--config", "/etc/grafana/grafana.ini"]
  wiki-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ../data/wiki-data/db-data:/var/lib/postgresql/data
  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - wiki-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "8097:3000"
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../data/caddy_data:/data
volumes:
  jellyfin_data:
  qbittorrent_data:
  prometheus_data:
  grafana_data:
  db-data:
  caddy_data: