version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus

    ports:
      - 9090:9090
    command: ["--config.file=/etc/prometheus/prometheus.yml"]

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana_data:/var/lib/grafana
    ports:
      - 3001:3001
    command: ["--config", "/etc/grafana/grafana.ini"]
volumes:
  prometheus_data:
  grafana_data: