global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'home-server-prometheus'
    static_configs:
      - targets: ['host.docker.internal:9093', 'node-exporter:9100']
