{
 "title": "HomeServer Main Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "HomeServer_BizBuySellRunnable_Crashed",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(HomeServer_BizBuySellRunnable_Crashed_total[1h])",
     "legendFormat": "Crashed [1hr Aggregated]"
    },
    {
     "expr": "increase(HomeServer_BizBuySellRunnable_Crashed_total[24h])",
     "legendFormat": "Crashed [24hr Aggregated]"
    }
   ]
  },
  {
   "title": "HomeServer_BizBuySellRunnable_State",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "HomeServer_BizBuySellRunnable_State",
     "legendFormat": "{{HomeServer_BizBuySellRunnable_State}}"
    }
   ]
  },
  {
   "title": "HomeServer_NewListingsPuller",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(HomeServer_NewListingsPuller_NewListingsStored_total[24h])",
     "legendFormat": "NewListingsStored [24hr Aggregated]"
    },
    {
     "expr": "increase(HomeServer_NewListingsPuller_ExistingListingsUpdated_total[24h])",
     "legendFormat": "ExistingListingsUpdated [24hr Aggregated]"
    }
   ]
  },
  {
   "title": "HomeServer_SoldListingsSweeper",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "increase(HomeServer_SoldListingsSweeper_MarkedSold_total[24h])",
     "legendFormat": "MarkedSold [24hr Aggregated]"
    },
    {
     "expr": "increase(HomeServer_SoldListingsSweeper_UpdatedLastSeen_total[24h])",
     "legendFormat": "UpdatedLastSeen [24hr Aggregated]"
    }
   ]
  }
 ]
}